version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - scan-vulnerabilities-by-snyk

jobs:
  scan-vulnerabilities-by-snyk:
    docker:
      - image: 'circleci/openjdk:11.0.3-jdk-stretch'
    steps:
      - checkout
      - snyk/scan
          fail-on-issues: 'false'
          monitor-on-build: 'true'
          severity-threshold: 'high'
          token-variable: ${SNYK_TOKEN}
orbs:
  snyk: snyk/snyk@0.0.10