version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - snyk

jobs:
  snyk:
    docker:
      - image: 'circleci/node:4.8.2'
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan
orbs:
  snyk: snyk/snyk@0.0.10