version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - scan-vulnerabilities-by-snyk
      - notify-slack

jobs:
  scan-vulnerabilities-by-snyk:
    docker:
      - image: 'circleci/openjdk:11.0.3-jdk-stretch'
    steps:
      - checkout
      - snyk/scan

  notify-slack:
    docker:
      - image: 'circleci/openjdk:11.0.3-jdk-stretch'
    steps:
      - slack/status:
          success_message: ':tada: build successful!!'
          failure_message: ':red_circle: build failed...'
          webhook: $SLACK_WEBHOOK

orbs:
  snyk: snyk/snyk@0.0.10
  slack: circleci/slack@3.4.2