/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import software.amazon.awscdk.core.App
import software.amazon.awscdk.core.Environment
import software.amazon.awscdk.core.StackProps

fun main() {
    val app = App()
    SnykUserStack(
        app, "SnykUserStack",
        StackProps.builder()
            .env(
                Environment.builder()
                    .account(System.getenv("CDK_DEFAULT_ACCOUNT"))
                    .region(System.getenv("CDK_DEFAULT_REGION"))
                    .build()
            )
            .build()
    )

    app.synth()

}
